spring:
  application:
    name: gateway-server
  profiles:
    active: dev
  config:
    import: optional:configserver:http://config-server:9991
  cloud:
    config:
      profile: dev
      request-connect-timeout: 5000
      request-read-timeout: 15000
      retry:
        max-attempts: 12
        initial-interval: 1000
        multiplier: 1.5
        max-interval: 5000

server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka