eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
spring:
  application:
    name: airline-service
  profiles:
    active: dev

  config:
    active:
      on-profile: dev
    import: optional:configserver:http://config-server:9991